# Generated by Django 4.2 on 2023-04-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_price_purchase_age_alter_purchase_date_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупок', 'verbose_name_plural': 'Покупки'},
        ),
    ]
